# Basic
title: 小飞
subtitle: Crazy_For_Coding
description: Let life be beautiful like summer flowers and death like autumn leaves。
# 头像里面的标题
avatarTitle: Jhon Nash
# 头像里面的描述
avatarDesc: 垂涎python的小飞
# url: "http://16110905035.github.io"
# url: "http://www.enjoy-life.top"
url: "https://whywhathow.github.io"
# Comment
# comment:
#     disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    # weibo: 1246389103
    github: 16110905035
    # twitter:
    mail: 1246389103@qq.com

# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: bdde692cc84921350d1365e49c1d4968

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3
#     host: auto


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 关于我, description: about, url: '/about'}


# Pagination
# plugins: [jekyll-paginate,jekyll-sitemap]

plugins_dir: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
plugins: [jekyll-paginate]
